---
# Playbook 3: Docker Container Management
- name: Manage Docker Containers and Images
  hosts: all
  become: yes
  vars:
    docker_version: latest
    container_registry: docker.io
    containers:
      - {name: 'app-web', image: 'nginx:latest', ports: '80:80', volumes: '/app:/var/www/html'}
      - {name: 'app-api', image: 'python:3.9', ports: '8000:8000'}
  
  tasks:
    - name: Install Docker and dependencies
      block:
        - apt: name={{item}} update_cache=yes
          loop: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]
        - apt_key: url=https://download.docker.com/linux/ubuntu/gpg
        - apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
        - apt: name=docker-ce state=present
      when: ansible_os_family == 'Debian'
    
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    
    - name: Start Docker service
      service: name=docker enabled=yes state=started
    
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    
    - name: Pull Docker images
      docker_image:
        name: "{{ item.image }}"
        source: pull
      loop: "{{ containers }}"
    
    - name: Create containers
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        ports: "{{ item.ports }}"
        volumes: "{{ item.get('volumes', []) }}"
        state: started
        restart_policy: always
      loop: "{{ containers }}"
    
    - name: Create Docker volumes
      docker_volume:
        name: "{{ item }}"
      loop: [app-data, logs-data]
    
    - name: Create Docker networks
      docker_network:
        name: "{{ item }}"
        driver: bridge
      loop: [app-network]
    
    - name: Verify Docker installation
      shell: |
        docker --version
        docker ps -a
      register: docker_status
    
    - name: Display Docker status
      debug: msg="{{ docker_status.stdout_lines }}"
